# Generated by Django 3.0.7 on 2020-07-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20200701_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='is_html',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='is_plaintxt',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='status',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='updated',
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='from_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='to_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
