# Generated by Django 3.0.7 on 2020-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200, null=True, unique=True)),
                ('backend_type', models.CharField(max_length=200, null=True)),
                ('sg_api_key', models.CharField(blank=True, max_length=225, null=True)),
                ('access_key_id', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_access_key', models.CharField(blank=True, max_length=255, null=True)),
                ('region_name', models.CharField(blank=True, max_length=255, null=True)),
                ('region_endpoint', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
