# Generated by Django 3.0.7 on 2020-07-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_with_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profile'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recipient',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sender',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subject',
            field=models.CharField(default='', max_length=120),
        ),
    ]
