# Generated by Django 3.0.7 on 2020-08-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
