# Generated by Django 3.0.7 on 2020-08-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20200804_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='logo',
            new_name='icon',
        ),
    ]
